import React, { useCallback } from 'react';
import { View, Text, StyleSheet, ActivityIndicator, Pressable } from 'react-native';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { Stack } from 'expo-router';

import { Screen } from '@/components/Screen';
import { SectionLabel } from '@/components/SectionLabel';
import { EmptyState } from '@/components/EmptyState';
import { colors, font, glow, radius, spacing } from '@/constants/colors';
import { useAuth } from '@/contexts/AuthContext';
import { apiGet, type CoachReport } from '@/lib/api';

function fmtPnl(v: number): string {
  const sign = v > 0 ? '+' : '';
  return `${sign}${v.toFixed(2)}%`;
}

function timeAgo(iso: string): string {
  try {
    const ms = Date.now() - new Date(iso).getTime();
    if (ms < 60_000) return 'just now';
    if (ms < 3_600_000) return `${Math.floor(ms / 60_000)}m ago`;
    if (ms < 86_400_000) return `${Math.floor(ms / 3_600_000)}h ago`;
    return `${Math.floor(ms / 86_400_000)}d ago`;
  } catch {
    return '';
  }
}

export default function CoachScreen() {
  const { uid } = useAuth();
  const qc = useQueryClient();

  const reportQ = useQuery({
    queryKey: ['coach-weekly', uid],
    queryFn: () => apiGet<CoachReport>('/api/coach/weekly', uid),
    enabled: !!uid,
  });

  const refreshM = useMutation({
    mutationFn: () => apiGet<CoachReport>('/api/coach/weekly', uid, { force: 1 }),
    onSuccess: (data) => {
      qc.setQueryData(['coach-weekly', uid], data);
    },
  });

  const onRefresh = useCallback(() => reportQ.refetch(), [reportQ]);

  const r = reportQ.data;
  const isLoading = reportQ.isLoading;
  const isError = reportQ.isError;

  return (
    <Screen
      title="AI Trade Coach"
      subtitle="Weekly review of your trades, generated by Claude."
      refreshing={reportQ.isFetching && !isLoading}
      onRefresh={onRefresh}
      ambient="duo"
    >
      <Stack.Screen options={{ title: 'Coach' }} />

      {isLoading ? (
        <View style={styles.loading}>
          <ActivityIndicator color={colors.accent} size="large" />
        </View>
      ) : isError ? (
        <EmptyState
          icon="cloud-offline-outline"
          title="Couldn't load your weekly review"
          hint="Pull down to retry."
        />
      ) : r ? (
        <>
          {/* Header card with stats */}
          <View style={styles.headerCard}>
            <View style={styles.headerRow}>
              <Text style={styles.headerLabel}>Week of {r.week_start}</Text>
              <View style={styles.metaChip}>
                <Ionicons
                  name={r.cached ? 'archive-outline' : 'sparkles'}
                  size={11}
                  color={colors.textMute}
                />
                <Text style={styles.metaChipText}>
                  {r.cached ? 'cached' : 'fresh'} · {timeAgo(r.generated_at)}
                </Text>
              </View>
            </View>

            <Text style={[styles.headerPnl, { color: r.stats.pnl_pct > 0 ? colors.positive : r.stats.pnl_pct < 0 ? colors.negative : colors.text }]}>
              {fmtPnl(r.stats.pnl_pct)}
            </Text>
            <Text style={styles.headerSub}>
              {r.stats.trades} closed · {r.stats.wins}W / {r.stats.losses}L · {r.stats.win_rate.toFixed(0)}% win
            </Text>

            {(r.stats.best || r.stats.worst) ? (
              <View style={styles.bestWorstRow}>
                {r.stats.best ? (
                  <View style={styles.bestWorstCell}>
                    <Text style={styles.bestWorstLabel}>BEST</Text>
                    <Text style={[styles.bestWorstValue, { color: colors.positive }]}>
                      {r.stats.best.symbol} {fmtPnl(r.stats.best.pnl_pct)}
                    </Text>
                  </View>
                ) : null}
                {r.stats.worst ? (
                  <View style={styles.bestWorstCell}>
                    <Text style={styles.bestWorstLabel}>WORST</Text>
                    <Text style={[styles.bestWorstValue, { color: colors.negative }]}>
                      {r.stats.worst.symbol} {fmtPnl(r.stats.worst.pnl_pct)}
                    </Text>
                  </View>
                ) : null}
              </View>
            ) : null}
          </View>

          {/* AI summary */}
          <View style={styles.section}>
            <SectionLabel label="Summary" tone="violet" />
            <View style={styles.bodyCard}>
              <Text style={styles.summaryText}>{r.summary}</Text>
            </View>
          </View>

          {/* Patterns */}
          {r.patterns.length > 0 ? (
            <View style={styles.section}>
              <SectionLabel label="Patterns this week" tone="accent" />
              <View style={styles.bodyCard}>
                {r.patterns.map((p, i) => (
                  <View key={`p-${i}`} style={[styles.bulletRow, i > 0 && styles.bulletRowDiv]}>
                    <Ionicons name="search" size={14} color={colors.accent} style={{ marginTop: 2 }} />
                    <Text style={styles.bulletText}>{p}</Text>
                  </View>
                ))}
              </View>
            </View>
          ) : null}

          {/* Recommendations */}
          {r.recommendations.length > 0 ? (
            <View style={styles.section}>
              <SectionLabel label="Recommendations" tone="positive" />
              <View style={styles.bodyCard}>
                {r.recommendations.map((rec, i) => (
                  <View key={`r-${i}`} style={[styles.bulletRow, i > 0 && styles.bulletRowDiv]}>
                    <Ionicons name="checkmark-circle" size={14} color={colors.positive} style={{ marginTop: 2 }} />
                    <Text style={styles.bulletText}>{rec}</Text>
                  </View>
                ))}
              </View>
            </View>
          ) : null}

          {/* Missed exits */}
          {r.missed_exits.length > 0 ? (
            <View style={styles.section}>
              <SectionLabel label="Missed exits" tone="warning" />
              <View style={styles.bodyCard}>
                {r.missed_exits.map((m, i) => (
                  <View key={`m-${i}`} style={[styles.bulletRow, i > 0 && styles.bulletRowDiv]}>
                    <Ionicons name="alert-circle" size={14} color={colors.warning} style={{ marginTop: 2 }} />
                    <Text style={styles.bulletText}>{m}</Text>
                  </View>
                ))}
              </View>
            </View>
          ) : null}

          {/* Refresh CTA — rate-limited server-side to once per 24h */}
          <Pressable
            onPress={() => refreshM.mutate()}
            disabled={refreshM.isPending}
            style={({ pressed }) => [
              styles.refreshBtn,
              pressed && { opacity: 0.85 },
              refreshM.isPending && { opacity: 0.6 },
            ]}
          >
            {refreshM.isPending ? (
              <ActivityIndicator color={colors.text} size="small" />
            ) : (
              <>
                <Ionicons name="refresh" size={15} color={colors.text} />
                <Text style={styles.refreshBtnText}>Regenerate review</Text>
              </>
            )}
          </Pressable>
          <Text style={styles.refreshHint}>
            Rate-limited to once per 24 hours to keep AI costs low.
          </Text>

          {r.stub ? (
            <View style={styles.stubBanner}>
              <Ionicons name="information-circle" size={16} color={colors.warning} />
              <Text style={styles.stubText}>
                Not enough closed trades this week for a full AI review. Keep your strategies running and check back next week.
              </Text>
            </View>
          ) : null}
        </>
      ) : null}
    </Screen>
  );
}

const styles = StyleSheet.create({
  loading: {
    paddingVertical: spacing.xxl + spacing.lg,
    alignItems: 'center',
  },
  headerCard: {
    backgroundColor: colors.card,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    ...glow.card,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLabel: {
    color: colors.textMute,
    fontFamily: font.bold,
    fontSize: 11,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  metaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: radius.pill,
    backgroundColor: colors.bgElev,
    borderWidth: 1,
    borderColor: colors.border,
  },
  metaChipText: {
    color: colors.textMute,
    fontFamily: font.medium,
    fontSize: 10,
    letterSpacing: 0.2,
  },
  headerPnl: {
    fontFamily: font.black,
    fontSize: 36,
    fontVariant: ['tabular-nums'],
    letterSpacing: -1,
    marginTop: spacing.sm,
  },
  headerSub: {
    color: colors.textDim,
    fontFamily: font.medium,
    fontSize: 13,
    marginTop: 4,
  },
  bestWorstRow: {
    flexDirection: 'row',
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    gap: spacing.md,
  },
  bestWorstCell: { flex: 1 },
  bestWorstLabel: {
    color: colors.textMute,
    fontFamily: font.bold,
    fontSize: 9.5,
    letterSpacing: 0.5,
  },
  bestWorstValue: {
    fontFamily: font.black,
    fontSize: 14,
    fontVariant: ['tabular-nums'],
    letterSpacing: -0.2,
    marginTop: 2,
  },
  section: { marginTop: spacing.xl },
  bodyCard: {
    backgroundColor: colors.card,
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    ...glow.card,
  },
  summaryText: {
    color: colors.text,
    fontFamily: font.regular,
    fontSize: 14,
    lineHeight: 20,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: spacing.sm,
  },
  bulletRowDiv: {
    borderTopWidth: 1,
    borderTopColor: colors.divider,
  },
  bulletText: {
    flex: 1,
    color: colors.text,
    fontFamily: font.regular,
    fontSize: 13.5,
    lineHeight: 19,
  },
  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: spacing.xl,
    paddingVertical: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: colors.bgElev,
    borderWidth: 1,
    borderColor: colors.border,
  },
  refreshBtnText: {
    color: colors.text,
    fontFamily: font.bold,
    fontSize: 14,
  },
  refreshHint: {
    color: colors.textMute,
    fontFamily: font.regular,
    fontSize: 11,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
  stubBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: spacing.lg,
    backgroundColor: 'rgba(245,158,11,0.08)',
    borderColor: 'rgba(245,158,11,0.28)',
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: spacing.md,
  },
  stubText: {
    flex: 1,
    color: colors.text,
    fontFamily: font.regular,
    fontSize: 12.5,
    lineHeight: 17,
  },
});
